server_event!(Away,    "AWAY",    "", 0: "Sender", 1: "\"AWAY\"",    eol 2: "Reason");
server_event!(Invite,  "INVITE",  "", 0: "Sender", 1: "\"INVITE\"",      2: "Target",  eol 3: "Channel");
server_event!(Join,    "JOIN",    "", 0: "Sender", 1: "\"JOIN\"",        2: "Channel",     3: "Account", eol 4: "Realname");
server_event!(Kick,    "KICK",    "", 0: "Sender", 1: "\"KICK\"",        2: "Channel",     3: "Target",  eol 4: "Reason");
server_event!(Kill,    "KILL",    "", 0: "Sender", 1: "\"KILL\"",        2: "Target",  eol 3: "Reason");
server_event!(Mode,    "MODE",    "", 0: "Sender", 1: "\"MODE\"",        2: "Target",      3: "Modes",   eol 4: "Arguments");
server_event!(Nick,    "NICK",    "", 0: "Sender", 1: "\"NICK\"",    eol 2: "Nickname");
server_event!(Notice,  "NOTICE",  "", 0: "Sender", 1: "\"NOTICE\"",      2: "Target",  eol 3: "Text");
server_event!(Part,    "PART",    "", 0: "Sender", 1: "\"PART\"",        2: "Channel", eol 3: "Reason");
server_event!(Ping,    "PING",    "", 0: "Sender", 1: "\"PING\"",    eol 2: "Server");
server_event!(Pong,    "PONG",    "", 0: "Sender", 1: "\"PONG\"",        2: "Server",  eol 3: "Timestamp");
server_event!(Privmsg, "PRIVMSG", "", 0: "Sender", 1: "\"PRIVMSG\"",     2: "Target",  eol 3: "Text");
server_event!(Quit,    "QUIT",    "", 0: "Sender", 1: "\"QUIT\"",    eol 2: "Reason");
server_event!(Topic,   "TOPIC",   "", 0: "Sender", 1: "\"TOPIC\"",       2: "Target",  eol 3: "Topic");
server_event!(Wallops, "WALLOPS", "", 0: "Sender", 1: "\"WALLOPS\"", eol 2: "Text");
